name = "phukhao-landing"
compatibility_date = "2025-06-01"
account_id = "a5eabdc2b11aae9bd5af46bd6a88179e"
workers_dev = true

routes = [
  { pattern = "phukhao.buildwithoracle.com", custom_domain = true }
]

[assets]
directory = "./dist"
